title: EthNow
description: The Ethereum Integration for ServiceNow
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
show_downloads: false
author:
  twitter: nicolaattico
github:
  is_project_page: false
